[build]
  functions = "server"
  publish = "client"
  command = "npm install && ./node_modules/.bin/prisma generate --schema=./prisma/schema.prisma && ./node_modules/.bin/prisma migrate deploy --schema=./prisma/schema.prisma"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200
  
[[redirects]]
  from = "/user/*"
  to = "/user.html"
  status = 200

[[redirects]]
  from = "/character/:id"
  to = "/character_detail.html"
  status = 200
