[build]
  functions = "server"
  publish = "client"
  command = "npm install && node node_modules/prisma/build/index.js generate --schema=./prisma/schema.prisma && node node_modules/prisma/build/index.js migrate deploy --schema=./prisma/schema.prisma && node scripts/build-static-data.js && node scripts/build-leaderboard.js"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200
  
[[redirects]]
  from = "/user/*"
  to = "/user.html"
  status = 200

[[redirects]]
  from = "/character/:id"
  to = "/character_detail.html"
  status = 200

[[redirects]]
  from = "/weapon/:id"
  to = "/weapon_detail.html"
  status = 200

[[redirects]]
  from = "/titan/:skillId/:titanName"
  to = "/titan_detail.html"
  status = 200

[[redirects]]
  from = "/titan/:skillId"
  to = "/titan_list.html"
  status = 200
